### ISSUE TITLE
WARNING: Encountered a problem while trying to record telemetry events

### ISSUE THREAD

**Issue by mrboring** [microsoft/PowerShellForGitHub#304]
#### Issue Details

Created this issue as requested in the warning below. It happened within an hour prior to 29 ‎November ‎2020, ‏‎19:47:01.

```
WARNING: Encountered a problem while trying to record telemetry events.
This is non-fatal, but it would be helpful if you could report this problem
to the PowerShellForGitHub team for further investigation:

Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

#### Steps to reproduce the issue

Not sure exactly what point in my code the issue happened. I was either creating an: issue, comment or log.
```

#### Verbose logs showing the problem

```
[92mException             : [0m
    [92mType       : [0mMicrosoft.PowerShell.Commands.HttpResponseException
    [92mResponse   : [0mStatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
                 {
                 Cache-Control: private
                 Date: Sun, 29 Nov 2020 19:44:30 GMT
                 Content-Type: text/html; charset=utf-8
                 Content-Length: 5864
                 }
    [92mTargetSite : [0m
        [92mName          : [0mThrowTerminatingError
        [92mDeclaringType : [0mSystem.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        [92mMemberType    : [0mMethod
        [92mModule        : [0mSystem.Management.Automation.dll
    [92mStackTrace : [0m
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
    [92mMessage    : [0mResponse status code does not indicate success: 500 (Internal Server Error).
    [92mSource     : [0mSystem.Management.Automation
    [92mHResult    : [0m-2146233088
[92mTargetObject          : [0mMethod: POST, RequestUri: 'https://dc.services.visualstudio.com/v2/track', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
                        {
                        User-Agent: Mozilla/5.0
                        User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.19042; en-GB)
                        User-Agent: PowerShell/7.1.0
                        Content-Length: 1643
                        Content-Type: application/json; charset=UTF-8
                        }
[92mCategoryInfo          : [0mInvalidOperation: (Method: POST, Reque…n; charset=UTF-8
                        }:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
[92mFullyQualifiedErrorId : [0mWebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
[92mErrorDetails          : [0m 
 
 
IIS 10.0 Detailed Error - 500.1013 - Internal Server Error 
 
 
 
 
 
 
 
 
  HTTP Error 500.1013 - Internal Server Error 
  The page cannot be displayed because an internal server error has occurred. 
 
 
 Most likely causes: 
   	IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred. 	IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly. 	IIS was not able to process configuration for the Web site or application. 	The authenticated user does not have permission to use this DLL. 	The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.  
  
 
 
 Things you can try: 
   	Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account. 	Check the event logs to see if any additional information was logged. 	Verify the permissions for the DLL. 	Install the .NET Extensibility feature if the request is mapped to a managed handler. 	Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click here.   
  
 
 
 
 Detailed Error Information: 
   
    
    Module&nbsp;&nbsp;&nbsp;iisnode 
    Notification&nbsp;&nbsp;&nbsp;ExecuteRequestHandler 
    Handler&nbsp;&nbsp;&nbsp;iisnode 
    Error Code&nbsp;&nbsp;&nbsp;0x0000006d 
     
    
   
   
    
    Requested URL&nbsp;&nbsp;&nbsp;https://dc.services.visualstudio.com:443/InputServer.js 
    Physical Path&nbsp;&nbsp;&nbsp;F:\sitesroot\0\InputServer.js 
    Logon Method&nbsp;&nbsp;&nbsp;Anonymous 
    Logon User&nbsp;&nbsp;&nbsp;Anonymous 
    Request Tracing Directory&nbsp;&nbsp;&nbsp;C:\Resources\directory\803b9fb6d5ea4de0af6a7fef06b9fbfc.Breeze.DiagnosticStore\FailedReqLogFiles\Web 
    
    
   
  
 
 
 
 More Information: 
  This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
  View more information &raquo; 
  Microsoft Knowledge Base Articles: 
 294807 
 
  
 
 
 
 

[92mInvocationInfo        : [0m
    [92mMyCommand        : [0mInvoke-WebRequest
    [92mScriptLineNumber : [0m173
    [92mOffsetInLine     : [0m16
    [92mHistoryId        : [0m7320
    [92mScriptName       : [0mC:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\Telemetry.ps1
    [92mLine             : [0mreturn Invoke-WebRequest @params
                       
    [92mPositionMessage  : [0mAt C:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\Telemetry.ps1:173 char:16
                       +         return Invoke-WebRequest @params
                       +                ~~~~~~~~~~~~~~~~~~~~~~~~~
    [92mPSScriptRoot     : [0mC:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1
    [92mPSCommandPath    : [0mC:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\Telemetry.ps1
    [92mInvocationName   : [0mInvoke-WebRequest
    [92mCommandOrigin    : [0mInternal
[92mScriptStackTrace      : [0mat Invoke-SendTelemetryEvent, C:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\Telemetry.ps1: line 173
                        at Set-TelemetryEvent, C:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\Telemetry.ps1: line 339
                        at Invoke-GHRestMethod, C:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\GitHubCore.ps1: line 306
                        at New-GitHubIssue, C:\Users\<removed>\Documents\PowerShell\Modules\PowerShellForGitHub\0.15.1\GitHubIssues.ps1: line 631
                        at New-ATGitHubIssue, C:\Data\PowerShell\Miscellaneous\PowerShellForGitHub\Import from BitBucket.ps1: line 52
                        at <ScriptBlock>, C:\Data\PowerShell\Miscellaneous\PowerShellForGitHub\Import from BitBucket.ps1: line 155
```

#### Operating System

```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}
```

#### PowerShell Version

```

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#### Module Version

```
Running:
Installed: 0.15.1
```

**Comment by HowardWolosky** [comment]
Thanks for the report.  Based on the content in that log, it appears that the error occurred because the telemetry endpoint was down for a brief period of time:

```
  HTTP Error 500.1013 - Internal Server Error 
  The page cannot be displayed because an internal server error has occurred. 
 
 Most likely causes: 
   	IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred. 	IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly. 	IIS was not able to process configuration for the Web site or application. 	The authenticated user does not have permission to use this DLL. 	The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.  
```

Given that it's not reproing at the moment, it looks like it was an intermittent issue that is non-actionable on our end.

I appreciate the report however.  Thanks for that!  Please do submit another report if you see this again.
